package com.djibtout.backend.service;
import com.djibtout.backend.entity.*;import com.djibtout.backend.repository.*;import org.springframework.stereotype.Service;
@Service public class SellerAccessService{
 private final SellerStaffRepository staff;public SellerAccessService(SellerStaffRepository s){staff=s;}
 public boolean canManageCatalog(User user,Product product){if(user==null)return false;if(user.getRole()==Role.ADMIN)return true;if(product.getSeller()!=null&&product.getSeller().getId().equals(user.getId()))return true;return staff.findByUser(user).stream().anyMatch(x->x.getStore().getSeller().getId().equals(product.getSeller().getId())&&(x.getStaffRole()==SellerStaffRole.STORE_MANAGER||x.getStaffRole()==SellerStaffRole.CATALOG_MANAGER));}
 public User ownerForCatalog(User user){if(user==null)return null;if(user.getRole()==Role.SELLER)return user;if(user.getRole()==Role.ADMIN)return user;return staff.findByUser(user).stream().filter(x->x.getStaffRole()==SellerStaffRole.STORE_MANAGER||x.getStaffRole()==SellerStaffRole.CATALOG_MANAGER).map(x->x.getStore().getSeller()).findFirst().orElse(null);}
 public User ownerForSupport(User user){if(user==null)return null;if(user.getRole()==Role.SELLER||user.getRole()==Role.ADMIN)return user;return staff.findByUser(user).stream().filter(x->x.getStaffRole()==SellerStaffRole.STORE_MANAGER||x.getStaffRole()==SellerStaffRole.SUPPORT).map(x->x.getStore().getSeller()).findFirst().orElse(null);}
 public boolean canSupport(User user,User seller){if(user==null||seller==null)return false;if(user.getRole()==Role.ADMIN||seller.getId().equals(user.getId()))return true;return staff.findByUser(user).stream().anyMatch(x->x.getStore().getSeller().getId().equals(seller.getId())&&(x.getStaffRole()==SellerStaffRole.STORE_MANAGER||x.getStaffRole()==SellerStaffRole.SUPPORT));}
 public User ownerForOrders(User user){if(user==null)return null;if(user.getRole()==Role.SELLER||user.getRole()==Role.ADMIN)return user;return staff.findByUser(user).stream().filter(x->x.getStaffRole()==SellerStaffRole.STORE_MANAGER||x.getStaffRole()==SellerStaffRole.ORDER_MANAGER).map(x->x.getStore().getSeller()).findFirst().orElse(null);}
 public boolean canManageOrders(User user,User seller){if(user==null||seller==null)return false;if(user.getRole()==Role.ADMIN||seller.getId().equals(user.getId()))return true;return staff.findByUser(user).stream().anyMatch(x->x.getStore().getSeller().getId().equals(seller.getId())&&(x.getStaffRole()==SellerStaffRole.STORE_MANAGER||x.getStaffRole()==SellerStaffRole.ORDER_MANAGER));}
}
