import Link from "next/link";
import Image from "next/image";
import {Suspense} from "react";
import {ArrowRight,Gift,Layers3,ShieldCheck,ShoppingBasket,ShoppingCart,Sparkles,Star,Tag,Truck,Zap} from "lucide-react";
import {fetchBestSellers,fetchCampaigns,fetchCatalogMetadata,fetchHomeSections,fetchProducts,HomeSection,Product} from "@/lib/api";
import DjibtoutProductCard from "@/components/DjibtoutProductCard";
import HomeHero from "@/components/HomeHero";
import RevealSection from "@/components/RevealSection";
import PersonalizedHomeShelves from "@/components/PersonalizedHomeShelves";
import HomeSectionSkeleton from "@/components/HomeSectionSkeleton";
import type {Metadata} from "next";

export const metadata:Metadata={title:"DjibTout — Marketplace et achats en ligne à Djibouti",description:"Découvrez les produits disponibles à Djibouti, comparez les prix et commandez auprès des vendeurs DjibTout."};

const DEFAULT_SECTIONS:HomeSection[]=[
  ["hero","À la une",0,14],["shortcuts","Services rapides",1,6],["categories","Catégories populaires",2,10],
  ["campaigns","Campagnes DjibTout",3,3],["popular","Produits populaires",4,10],["best_sellers","Meilleures ventes",5,10],
  ["limited_offers","Offres limitées",6,10],["newest","Nouveautés",7,10],["category_selections","Sélections par catégorie",8,10],
  ["recently_viewed","Récemment consultés",9,10],["recommended","Recommandés pour vous",10,10],["brands","Marques populaires",11,6],
  ["seo","Acheter en ligne à Djibouti",12,1],["faq","Questions fréquentes",13,6],
].map(([key,title,displayOrder,maxItems],index)=>({id:-(index+1),key:key as string,title:title as string,active:true,displayOrder:displayOrder as number,maxItems:maxItems as number}));

const shortcuts=[
  {label:"Super offres",copy:"Prix avantageux",icon:Zap,href:"/search?sort=price_asc",tone:"bg-red-50 text-red-600"},
  {label:"Coupons",copy:"Réductions actives",icon:Tag,href:"/account/coupons",tone:"bg-violet-50 text-violet-600"},
  {label:"Livraison",copy:"Suivi à Djibouti",icon:Truck,href:"/search?inStock=true",tone:"bg-cyan-50 text-cyan-700"},
  {label:"Paiement sûr",copy:"Achats protégés",icon:ShieldCheck,href:"/checkout",tone:"bg-emerald-50 text-emerald-700"},
  {label:"Idées cadeaux",copy:"Pour faire plaisir",icon:Gift,href:"/search?q=cadeau",tone:"bg-pink-50 text-pink-600"},
  {label:"Nouveautés",copy:"Derniers arrivages",icon:Sparkles,href:"/search?sort=newest",tone:"bg-amber-50 text-amber-700"},
];

export default async function Home(){
  const configured=await fetchHomeSections();
  const sections=configured.length?configured:DEFAULT_SECTIONS;
  return <div className="min-h-screen pb-16"><h1 className="sr-only">DjibTout, marketplace et achats en ligne à Djibouti</h1><div className="dt-container space-y-7 py-4 sm:py-6">{sections.map(section=><Suspense key={section.key} fallback={<HomeSectionSkeleton type={section.key}/>}><ConfiguredSection config={section} allSections={sections}/></Suspense>)}</div></div>;
}

async function ConfiguredSection({config,allSections}:{config:HomeSection;allSections:HomeSection[]}){
  switch(config.key){
    case "hero": {const [campaigns,products]=await Promise.all([fetchCampaigns(),fetchProducts()]);const discounted=products.find(p=>(p.discountPercentage||0)>0);return <div className="grid items-stretch gap-5 lg:grid-cols-[minmax(0,1.85fr)_minmax(310px,.75fr)]"><HomeHero campaigns={campaigns}/><DealPanel product={discounted||products[0]}/></div>}
    case "shortcuts": return <nav className="flex snap-x gap-3 overflow-x-auto pb-2 [scrollbar-width:none] lg:grid lg:grid-cols-6" aria-label="Services DjibTout">{shortcuts.slice(0,config.maxItems).map(({label,copy,icon:Icon,href,tone})=><Link href={href} key={label} className="group flex min-w-[175px] snap-start items-center gap-3 rounded-2xl bg-white p-4 shadow-[0_8px_28px_rgba(17,39,72,.06)] ring-1 ring-slate-200/60 transition duration-300 hover:-translate-y-1 hover:shadow-[0_16px_36px_rgba(17,39,72,.12)] lg:min-w-0"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${tone} transition group-hover:scale-110`}><Icon size={20}/></span><span className="min-w-0"><strong className="block text-xs text-slate-800">{label}</strong><small className="mt-1 block truncate text-[10px] text-slate-500">{copy}</small></span></Link>)}</nav>;
    case "categories": {const data=await fetchCatalogMetadata();if(!data.categories.length)return null;return <RevealSection><SectionTitle title={config.title} subtitle={config.subtitle}/><div className="grid grid-cols-4 gap-3 rounded-[24px] bg-white p-4 shadow-[0_14px_45px_rgba(17,39,72,.06)] sm:grid-cols-6 sm:p-6 lg:grid-cols-10">{data.categories.slice(0,config.maxItems).map((category,index)=><Link key={category.value} href={`/search?category=${encodeURIComponent(category.value)}`} className="group min-w-0 rounded-2xl p-2 text-center transition hover:bg-slate-50"><span className={`mx-auto grid aspect-square w-full max-w-[88px] place-items-center rounded-[22px] bg-gradient-to-br ${["from-blue-50 to-sky-100","from-pink-50 to-rose-100","from-amber-50 to-yellow-100","from-violet-50 to-purple-100","from-emerald-50 to-green-100"][index%5]} transition duration-300 group-hover:-translate-y-1 group-hover:rotate-2 group-hover:shadow-lg`}><Layers3 size={28} className="text-[var(--primary)]"/></span><strong className="mt-3 block truncate text-[11px] capitalize text-slate-800">{category.value.replaceAll("-"," ")}</strong><small className="mt-1 block text-[9px] text-slate-400">{category.count} produits</small></Link>)}</div></RevealSection>}
    case "campaigns": {const campaigns=await fetchCampaigns();if(!campaigns.length)return null;return <RevealSection><SectionTitle title={config.title} subtitle={config.subtitle}/><div className="grid gap-5 md:grid-cols-3">{campaigns.slice(0,config.maxItems).map(c=><Link key={c.id} href={c.linkUrl} className={`group relative min-h-[230px] overflow-hidden rounded-[24px] bg-gradient-to-br ${c.gradient} p-7 text-white shadow-[0_18px_45px_rgba(17,39,72,.16)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_24px_55px_rgba(17,39,72,.22)]`}><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-white/10 transition duration-500 group-hover:scale-125"/><span className="relative rounded-full bg-white/15 px-3 py-1.5 text-[10px] font-black backdrop-blur">{c.badge}</span><h2 className="relative mt-8 text-2xl font-black tracking-tight">{c.title}</h2><p className="relative mt-2 text-xs leading-5 text-white/80">{c.subtitle}</p><span className="relative mt-5 inline-flex items-center gap-2 text-xs font-black">Découvrir <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></Link>)}</div></RevealSection>}
    case "best_sellers": {const products=await fetchBestSellers(config.maxItems);return products.length?<ProductShelf config={config} products={products} icon={<ShoppingCart size={19}/>}/>:null}
    case "popular": case "limited_offers": case "newest": {const products=await fetchProducts();let selected:Product[]=[];let icon=<Star size={19}/>;if(config.key==="popular")selected=[...products].filter(p=>(p.reviewCount||0)>0).sort((a,b)=>(b.averageRating||0)-(a.averageRating||0));if(config.key==="limited_offers"){selected=products.filter(p=>(p.discountPercentage||0)>0);icon=<Zap size={19}/>;}if(config.key==="newest"){selected=[...products].sort((a,b)=>b.id-a.id);icon=<Sparkles size={19}/>;}return selected.length?<ProductShelf config={config} products={selected.slice(0,config.maxItems)} icon={icon}/>:null}
    case "category_selections": {const [products,data]=await Promise.all([fetchProducts(),fetchCatalogMetadata()]);return <>{data.categories.slice(0,2).map(category=>{const selected=products.filter(p=>p.category===category.value).slice(0,config.maxItems);return selected.length?<ProductShelf key={category.value} config={{...config,title:`Sélection ${category.value.replaceAll("-"," ")}`,subtitle:`${category.count} produits disponibles`}} products={selected} icon={<Layers3 size={19}/>}/>:null})}</>}
    case "recently_viewed": case "recommended": {const products=await fetchProducts();return <PersonalizedHomeShelves products={products} sections={allSections} mode={config.key}/>}
    case "brands": {const [data,products]=await Promise.all([fetchCatalogMetadata(),fetchProducts()]);return <BrandDirectory metadata={data} productsCount={products.length} maxItems={config.maxItems}/>}
    case "seo": return <SeoEditorial title={config.title}/>;
    case "faq": return <HomeFaq title={config.title}/>;
    default:return null;
  }
}

function SectionTitle({title,subtitle}:{title:string;subtitle?:string}){return <div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="text-xl font-black tracking-[-.035em] text-slate-900 sm:text-2xl">{title}</h2>{subtitle&&<p className="mt-1.5 text-xs text-slate-500">{subtitle}</p>}</div><Link href="/search" className="flex shrink-0 items-center gap-1 rounded-full bg-blue-50 px-3 py-2 text-xs font-extrabold text-[var(--primary)] transition hover:bg-blue-100">Tout voir <ArrowRight size={14}/></Link></div>}
function ProductShelf({config,products,icon}:{config:HomeSection;products:Product[];icon:React.ReactNode}){return <RevealSection className="overflow-hidden rounded-[22px] bg-white shadow-[0_14px_45px_rgba(22,46,82,.07)]"><div className="px-5 pt-6 sm:px-7"><div className="flex items-center gap-2 text-[var(--primary)]">{icon}<SectionTitle title={config.title} subtitle={config.subtitle}/></div></div><div className="flex snap-x gap-px overflow-x-auto bg-slate-50/60 [scrollbar-width:none]">{products.map(product=><div key={product.id} className="min-w-[170px] max-w-[170px] snap-start bg-white sm:min-w-[226px] sm:max-w-[226px]"><DjibtoutProductCard product={product}/></div>)}</div></RevealSection>}
function DealPanel({product}:{product?:Product}){if(!product)return <aside className="hidden rounded-[28px] bg-white shadow-xl lg:block"/>;const raw=product.images?.[0]||product.imageUrl;const image=raw&&/^(https?:|\/|data:)/.test(raw)?raw:"/images/product-placeholder-premium-v2.png";return <aside className="hidden overflow-hidden rounded-[28px] bg-white shadow-[0_24px_65px_rgba(17,39,72,.13)] lg:flex lg:flex-col"><div className="bg-gradient-to-br from-[#075bd8] to-[#09a7b9] px-6 py-6 text-white"><small className="font-black tracking-[.18em] text-white/75">OFFRE DU MOMENT</small><h2 className="mt-1 text-2xl font-black tracking-tight">À ne pas manquer</h2></div><Link href={`/product/${product.id}`} className="flex flex-1 flex-col p-6"><div className="flex flex-1 flex-col items-center justify-center gap-5"><div className="grid aspect-square w-full place-items-center rounded-[22px] bg-gradient-to-br from-slate-50 to-blue-50"><Image src={image} alt={product.name} width={190} height={190} unoptimized={image.startsWith("http")||image.startsWith("data:")} className="h-48 w-48 object-contain transition duration-500 hover:scale-105"/></div><div className="w-full"><p className="line-clamp-2 text-sm font-semibold leading-6 text-slate-700">{product.name}</p><strong className="mt-2 block text-2xl font-black tracking-tight text-slate-950">{new Intl.NumberFormat("fr-DJ").format(product.price)} <small className="text-xs">FDJ</small></strong></div></div><span className="mt-5 flex h-12 items-center justify-center gap-2 rounded-full bg-[var(--primary)] text-sm font-black text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[var(--primary-hover)]"><ShoppingCart size={17}/>Voir le produit</span></Link></aside>}
function BrandDirectory({metadata,productsCount,maxItems}:{metadata:{categories:{value:string;count:number}[];brands:{value:string;count:number}[]};productsCount:number;maxItems:number}){return <RevealSection className="overflow-hidden rounded-lg border bg-[#fafafa]"><div className="grid md:grid-cols-[360px_1fr]"><div className="bg-[#252525] p-7 text-white"><ShoppingBasket className="text-blue-300"/><h2 className="mt-4 text-2xl font-black">Tout Djibouti dans un seul catalogue</h2><p className="mt-3 text-xs text-[#ccc]">{metadata.categories.length} catégories et {productsCount} produits disponibles.</p></div><div className="grid grid-cols-2 gap-px bg-[#e5e5e5] sm:grid-cols-3">{metadata.brands.slice(0,maxItems).map(brand=><Link href={`/search?q=${encodeURIComponent(brand.value)}`} key={brand.value} className="grid min-h-[105px] place-items-center bg-white p-4 text-center hover:bg-blue-50"><strong>{brand.value}<small className="block text-[#888]">{brand.count} produits</small></strong></Link>)}</div></div></RevealSection>}
function SeoEditorial({title}:{title:string}){return <RevealSection className="rounded-lg border bg-white p-6 sm:p-8"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 grid gap-5 text-sm leading-6 text-[#666] md:grid-cols-2"><p>DjibTout réunit des vendeurs et des produits disponibles à Djibouti dans un catalogue unique. Comparez les prix, consultez le stock réel et choisissez votre adresse de livraison.</p><p>Les informations de prix, de remise, de vendeur et de disponibilité proviennent directement du catalogue DjibTout.</p></div></RevealSection>}
function HomeFaq({title}:{title:string}){const questions=[{q:"Comment connaître le délai de livraison ?",a:"Le délai indicatif apparaît sur la fiche produit et dépend de l’adresse choisie."},{q:"Comment suivre une commande ?",a:"Vos commandes et leurs statuts sont disponibles depuis votre compte."},{q:"Les stocks affichés sont-ils réels ?",a:"Oui, la quantité disponible est vérifiée lors de la commande."},{q:"Puis-je utiliser un coupon ?",a:"Les coupons éligibles peuvent être appliqués au panier ou au checkout."}];const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:questions.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))};return <RevealSection className="rounded-lg border bg-white p-6 sm:p-8"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><h2 className="text-xl font-black">{title}</h2><div className="mt-4 divide-y">{questions.map(item=><details key={item.q} className="py-4"><summary className="cursor-pointer text-sm font-bold">{item.q}</summary><p className="mt-3 text-sm text-[#666]">{item.a}</p></details>)}</div></RevealSection>}
