"use client";

import Link from "next/link";
import { ChevronDown, ChevronRight, Laptop, Shirt, House, Car, Baby, Dumbbell, Sparkles, ShoppingBasket } from "lucide-react";

const categories = [
  {name:"Électronique",slug:"electronique",icon:Laptop, groups:[{title:"Informatique",links:["Ordinateurs portables","Tablettes","Imprimantes","Composants"]},{title:"Téléphones",links:["Smartphones","Accessoires","Montres connectées","Téléphones classiques"]},{title:"TV & Audio",links:["Téléviseurs","Casques","Enceintes","Jeux vidéo"]}]},
  {name:"Mode",slug:"mode",icon:Shirt,groups:[{title:"Femme",links:["Robes","Chaussures","Sacs","Accessoires"]},{title:"Homme",links:["T-shirts","Pantalons","Baskets","Montres"]},{title:"Enfant",links:["Filles","Garçons","Bébé","Chaussures"]}]},
  {name:"Maison & Bureau",slug:"maison",icon:House,groups:[{title:"Maison",links:["Meubles","Décoration","Linge de maison","Rangement"]},{title:"Cuisine",links:["Cuisson","Vaisselle","Petit électroménager","Conservation"]},{title:"Bureau",links:["Papeterie","Mobilier","Fournitures","Scolaire"]}]},
  {name:"Auto & Bricolage",slug:"auto-bricolage",icon:Car,groups:[{title:"Automobile",links:["Accessoires auto","Entretien","Pièces","Électronique auto"]},{title:"Bricolage",links:["Outillage","Quincaillerie","Électricité","Jardin"]}]},
  {name:"Maman & Bébé",slug:"maman-bebe",icon:Baby,groups:[{title:"Bébé",links:["Couches","Alimentation","Soins","Chambre"]},{title:"Jouets",links:["Jeux éducatifs","Construction","Poupées","Plein air"]}]},
  {name:"Sport",slug:"sport",icon:Dumbbell,groups:[{title:"Sports",links:["Fitness","Football","Running","Sports collectifs"]},{title:"Outdoor",links:["Camping","Randonnée","Cyclisme","Voyage"]}]},
  {name:"Beauté",slug:"beaute",icon:Sparkles,groups:[{title:"Beauté",links:["Parfums","Maquillage","Soins visage","Soins cheveux"]},{title:"Hygiène",links:["Corps","Dentaire","Homme","Accessoires"]}]},
  {name:"Supermarché",slug:"supermarche",icon:ShoppingBasket,groups:[{title:"Épicerie",links:["Boissons","Petit-déjeuner","Snacks","Conserves"]},{title:"Maison",links:["Nettoyage","Lessive","Papier","Animaux"]}]},
];

export default function NavigationMenu({mobile=false,onNavigate}:{mobile?:boolean;onNavigate?:()=>void}) {
  if(mobile) return <nav className="p-4"><p className="mb-3 text-xs font-extrabold uppercase tracking-wider text-slate-400">Toutes les catégories</p>{categories.map(({name,slug,icon:Icon})=><Link onClick={onNavigate} key={slug} href={`/category/${slug}`} className="flex items-center gap-3 border-b border-slate-100 py-3 text-sm font-bold text-slate-700"><Icon size={19} className="text-[var(--primary)]"/><span className="flex-1">{name}</span><ChevronRight size={16}/></Link>)}</nav>;
  return <div className="hidden border-y border-slate-200 bg-white lg:block"><div className="h-1 bg-gradient-to-r from-blue-800 via-[var(--primary)] to-cyan-400"/><nav className="dt-container flex h-[46px] items-stretch justify-between">{categories.map((category)=><div className="group relative flex-1" key={category.slug}><Link href={`/category/${category.slug}`} className="flex h-full items-center justify-center gap-1 border-x border-transparent px-2 text-center text-[12px] font-extrabold text-slate-700 transition hover:border-slate-200 hover:bg-slate-50 hover:text-[var(--primary)]">{category.name}<ChevronDown size={12}/></Link><div className="invisible absolute left-0 top-full w-[720px] translate-y-2 rounded-b-xl border border-slate-200 bg-white p-6 opacity-0 shadow-2xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-last:left-auto group-last:right-0"><div className="grid grid-cols-[1fr_1fr_1fr_210px] gap-6">{category.groups.map(group=><div key={group.title}><Link href={`/category/${category.slug}`} className="mb-3 block text-sm font-extrabold text-[var(--primary)]">{group.title}</Link><ul className="space-y-2">{group.links.map(link=><li key={link}><Link className="text-[13px] font-medium text-slate-600 hover:text-[var(--primary)] hover:underline" href={`/category/${category.slug}?q=${encodeURIComponent(link)}`}>{link}</Link></li>)}</ul></div>)}<Link href={`/category/${category.slug}`} className="col-start-4 row-start-1 row-span-2 flex min-h-[190px] flex-col justify-between rounded-xl bg-gradient-to-br from-blue-50 to-cyan-50 p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white text-[var(--primary)] shadow-sm"><category.icon size={24}/></span><span><strong className="block text-lg leading-tight text-slate-900">Tout l’univers {category.name}</strong><small className="mt-2 block font-bold text-[var(--primary)]">Découvrir maintenant →</small></span></Link></div></div></div>)}</nav></div>;
}
