--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    city character varying(100) NOT NULL,
    full_address character varying(500) NOT NULL,
    is_default boolean NOT NULL,
    label character varying(80) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(255),
    created_at timestamp(6) without time zone,
    target character varying(500),
    actor_id bigint
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaigns (
    id bigint NOT NULL,
    active boolean NOT NULL,
    badge character varying(50) NOT NULL,
    display_order integer NOT NULL,
    ends_at timestamp(6) without time zone,
    gradient character varying(120) NOT NULL,
    image_url character varying(255),
    link_url character varying(255) NOT NULL,
    starts_at timestamp(6) without time zone,
    subtitle character varying(240) NOT NULL,
    title character varying(100) NOT NULL
);


--
-- Name: campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campaigns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    active boolean NOT NULL,
    display_order integer NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(140) NOT NULL,
    parent_id bigint
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_attribute_values; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category_attribute_values (
    attribute_id bigint NOT NULL,
    value character varying(100)
);


--
-- Name: category_attributes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category_attributes (
    id bigint NOT NULL,
    name character varying(80) NOT NULL,
    required boolean NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: category_attributes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category_attributes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_attributes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(40) NOT NULL,
    discount_type character varying(255) NOT NULL,
    discount_value numeric(12,2) NOT NULL,
    expires_at timestamp(6) without time zone,
    usage_limit integer,
    used_count integer NOT NULL,
    CONSTRAINT coupons_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying])::text[])))
);


--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorites (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: home_sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_sections (
    id bigint NOT NULL,
    active boolean NOT NULL,
    category character varying(100),
    display_order integer NOT NULL,
    section_key character varying(60) NOT NULL,
    max_items integer NOT NULL,
    subtitle character varying(180),
    title character varying(100) NOT NULL
);


--
-- Name: home_sections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.home_sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.home_sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    delivery_address character varying(255) NOT NULL,
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    buyer_id bigint NOT NULL,
    coupon_code character varying(50),
    delivery_fee numeric(10,2),
    delivery_method character varying(30),
    discount_amount numeric(10,2),
    idempotency_key character varying(80),
    reserved_until timestamp(6) without time zone,
    subtotal_amount numeric(10,2),
    version bigint DEFAULT 0,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone,
    failure_reason character varying(255),
    payment_method character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    transaction_id character varying(255),
    order_id bigint NOT NULL
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    product_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: product_interactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_interactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    placement character varying(80),
    product_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    CONSTRAINT product_interactions_type_check CHECK (((type)::text = ANY ((ARRAY['IMPRESSION'::character varying, 'CLICK'::character varying])::text[])))
);


--
-- Name: product_interactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_interactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_interactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_questions (
    id bigint NOT NULL,
    answer character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    question character varying(500) NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    answered_at timestamp(6) without time zone,
    answered_by_id bigint,
    hidden boolean
);


--
-- Name: product_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_variant_attributes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_variant_attributes (
    variant_id bigint NOT NULL,
    attribute_value character varying(160),
    attribute_name character varying(80) NOT NULL
);


--
-- Name: product_variant_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_variant_images (
    variant_id bigint NOT NULL,
    image_url character varying(1000),
    display_order integer NOT NULL
);


--
-- Name: product_variants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_variants (
    id bigint NOT NULL,
    active boolean NOT NULL,
    price numeric(10,2) NOT NULL,
    sku character varying(80) NOT NULL,
    stock_quantity integer NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: product_variants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_variants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock_quantity integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    seller_id bigint NOT NULL,
    video_url character varying(255),
    visible boolean,
    brand character varying(100),
    delivery_days integer,
    original_price numeric(10,2),
    warranty_months integer,
    flash_sale_ends_at timestamp(6) without time zone,
    version bigint DEFAULT 0
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.refresh_tokens_id_seq OWNED BY public.refresh_tokens.id;


--
-- Name: return_evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_evidence (
    return_id bigint NOT NULL,
    image_url character varying(500)
);


--
-- Name: return_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    customer_comment character varying(1000),
    quantity integer NOT NULL,
    reason character varying(120) NOT NULL,
    refund_amount numeric(10,2) NOT NULL,
    seller_response character varying(1000),
    status character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone,
    buyer_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT return_requests_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'RECEIVED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: return_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    comment text NOT NULL,
    created_at timestamp(6) without time zone,
    rating integer NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    seller_responded_at timestamp(6) without time zone,
    seller_response character varying(1000),
    seller_responded_by_id bigint,
    hidden boolean
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_fulfillments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_fulfillments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255),
    tracking_number character varying(100),
    order_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT seller_fulfillments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: seller_fulfillments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_fulfillments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_fulfillments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message character varying(1000),
    read boolean NOT NULL,
    title character varying(255),
    seller_id bigint NOT NULL
);


--
-- Name: seller_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_settlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_settlements (
    id bigint NOT NULL,
    commission_amount numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone,
    gross_amount numeric(10,2) NOT NULL,
    net_amount numeric(10,2) NOT NULL,
    paid_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    fulfillment_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT seller_settlements_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'PAID'::character varying])::text[])))
);


--
-- Name: seller_settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_staff; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_staff (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    staff_role character varying(255) NOT NULL,
    store_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT seller_staff_staff_role_check CHECK (((staff_role)::text = ANY ((ARRAY['STORE_MANAGER'::character varying, 'CATALOG_MANAGER'::character varying, 'ORDER_MANAGER'::character varying, 'SUPPORT'::character varying])::text[])))
);


--
-- Name: seller_staff_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_stores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_stores (
    id bigint NOT NULL,
    banner_url character varying(255),
    description character varying(1000),
    logo_url character varying(255),
    name character varying(120) NOT NULL,
    policies character varying(1000),
    validated boolean NOT NULL,
    seller_id bigint NOT NULL,
    business_address character varying(500),
    business_document_url character varying(255),
    business_type character varying(255),
    identity_document_url character varying(255),
    phone character varying(255),
    registration_number character varying(255),
    onboarding_submitted boolean,
    terms_accepted boolean,
    version bigint DEFAULT 0
);


--
-- Name: seller_stores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_stores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_stores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    provider character varying(255),
    email_verification_token character varying(255),
    password_reset_expires_at timestamp(6) without time zone,
    password_reset_token character varying(255),
    email_verified boolean,
    account_deleted boolean,
    order_notifications boolean,
    phone character varying(30),
    promotion_notifications boolean,
    suspended boolean,
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying, 'FACEBOOK'::character varying, 'APPLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER'::character varying, 'SELLER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_transactions (
    id bigint NOT NULL,
    amount numeric(14,2) NOT NULL,
    created_at timestamp(6) without time zone,
    reason character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    wallet_id bigint NOT NULL,
    CONSTRAINT wallet_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying])::text[])))
);


--
-- Name: wallet_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    balance numeric(14,2) NOT NULL,
    version bigint,
    user_id bigint NOT NULL
);


--
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('public.refresh_tokens_id_seq'::regclass);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: campaigns campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: category_attributes category_attributes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_attributes
    ADD CONSTRAINT category_attributes_pkey PRIMARY KEY (id);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: home_sections home_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_sections
    ADD CONSTRAINT home_sections_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: product_interactions product_interactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_interactions
    ADD CONSTRAINT product_interactions_pkey PRIMARY KEY (id);


--
-- Name: product_questions product_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions
    ADD CONSTRAINT product_questions_pkey PRIMARY KEY (id);


--
-- Name: product_variant_attributes product_variant_attributes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variant_attributes
    ADD CONSTRAINT product_variant_attributes_pkey PRIMARY KEY (variant_id, attribute_name);


--
-- Name: product_variant_images product_variant_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variant_images
    ADD CONSTRAINT product_variant_images_pkey PRIMARY KEY (variant_id, display_order);


--
-- Name: product_variants product_variants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: return_requests return_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT return_requests_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: seller_fulfillments seller_fulfillments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_fulfillments
    ADD CONSTRAINT seller_fulfillments_pkey PRIMARY KEY (id);


--
-- Name: seller_notification seller_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_notification
    ADD CONSTRAINT seller_notification_pkey PRIMARY KEY (id);


--
-- Name: seller_settlements seller_settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlements
    ADD CONSTRAINT seller_settlements_pkey PRIMARY KEY (id);


--
-- Name: seller_staff seller_staff_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_staff
    ADD CONSTRAINT seller_staff_pkey PRIMARY KEY (id);


--
-- Name: seller_stores seller_stores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_stores
    ADD CONSTRAINT seller_stores_pkey PRIMARY KEY (id);


--
-- Name: users uk2rjv6idry5h6maepsmyvxqbli; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2rjv6idry5h6maepsmyvxqbli UNIQUE (password_reset_token);


--
-- Name: users uk6312a15kar8gic56s3csfavqx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6312a15kar8gic56s3csfavqx UNIQUE (email_verification_token);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: seller_fulfillments uk93epiod2jfvemou10qi8y6jta; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_fulfillments
    ADD CONSTRAINT uk93epiod2jfvemou10qi8y6jta UNIQUE (order_id, seller_id);


--
-- Name: orders uk_order_buyer_idempotency; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_order_buyer_idempotency UNIQUE (buyer_id, idempotency_key);


--
-- Name: home_sections ukcylt5ai1qpx0fkgjv2nj4adbf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_sections
    ADD CONSTRAINT ukcylt5ai1qpx0fkgjv2nj4adbf UNIQUE (section_key);


--
-- Name: coupons ukeplt0kkm9yf2of2lnx6c1oy9b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukeplt0kkm9yf2of2lnx6c1oy9b UNIQUE (code);


--
-- Name: seller_staff ukfu5b32xr4cy6fwl1mgi248slp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_staff
    ADD CONSTRAINT ukfu5b32xr4cy6fwl1mgi248slp UNIQUE (store_id, user_id);


--
-- Name: favorites ukgh1s14hhb9qb8p2do933hscsf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT ukgh1s14hhb9qb8p2do933hscsf UNIQUE (user_id, product_id);


--
-- Name: payments uklryndveuwa4k5qthti0pkmtlx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uklryndveuwa4k5qthti0pkmtlx UNIQUE (transaction_id);


--
-- Name: seller_settlements ukmmbch3u32uofqc8no8o4x908p; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlements
    ADD CONSTRAINT ukmmbch3u32uofqc8no8o4x908p UNIQUE (fulfillment_id);


--
-- Name: seller_stores uknj1bjneiw8yq6i51e3b4779n6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_stores
    ADD CONSTRAINT uknj1bjneiw8yq6i51e3b4779n6 UNIQUE (seller_id);


--
-- Name: product_variants ukotrdr01rrxy6fms8yuyd06jxx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT ukotrdr01rrxy6fms8yuyd06jxx UNIQUE (product_id, sku);


--
-- Name: categories ukoul14ho7bctbefv8jywp5v3i2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug);


--
-- Name: wallets uksswfdl9fq40xlkove1y5kc7kv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uksswfdl9fq40xlkove1y5kc7kv UNIQUE (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wallet_transactions wallet_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- Name: idx_product_interaction_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_interaction_created ON public.product_interactions USING btree (created_at);


--
-- Name: idx_product_interaction_product_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_interaction_product_type ON public.product_interactions USING btree (product_id, type);


--
-- Name: idx_question_product_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_question_product_created ON public.product_questions USING btree (product_id, created_at);


--
-- Name: idx_refresh_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_refresh_token_hash ON public.refresh_tokens USING btree (token_hash);


--
-- Name: addresses fk1fa36y2oqhao3wgg2rw1pi459; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: seller_fulfillments fk1p0y1sdj5rr9yq755cwpwxtu0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_fulfillments
    ADD CONSTRAINT fk1p0y1sdj5rr9yq755cwpwxtu0 FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: product_questions fk2316nred1rnt8ho92toi8cr43; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions
    ADD CONSTRAINT fk2316nred1rnt8ho92toi8cr43 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: seller_settlements fk27hs0wci5v6tp2yfv6vu41jpo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlements
    ADD CONSTRAINT fk27hs0wci5v6tp2yfv6vu41jpo FOREIGN KEY (fulfillment_id) REFERENCES public.seller_fulfillments(id);


--
-- Name: return_requests fk2qsp1rpmxbb3hpr6t3i2sdvdk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fk2qsp1rpmxbb3hpr6t3i2sdvdk FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: return_requests fk2x5c7kwyx72wwpm68d19xkoey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fk2x5c7kwyx72wwpm68d19xkoey FOREIGN KEY (buyer_id) REFERENCES public.users(id);


--
-- Name: product_questions fk6a2dr1vpm7dtolohd1ogi6nn7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions
    ADD CONSTRAINT fk6a2dr1vpm7dtolohd1ogi6nn7 FOREIGN KEY (answered_by_id) REFERENCES public.users(id);


--
-- Name: favorites fk6sgu5npe8ug4o42bf9j71x20c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fk6sgu5npe8ug4o42bf9j71x20c FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: reviews fk6uxiycgyhd8u0hh7isgupdd96; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk6uxiycgyhd8u0hh7isgupdd96 FOREIGN KEY (seller_responded_by_id) REFERENCES public.users(id);


--
-- Name: seller_notification fk7t8ls4oksen4wmbe6q6o4hpg3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_notification
    ADD CONSTRAINT fk7t8ls4oksen4wmbe6q6o4hpg3 FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: wallet_transactions fk8seu7b87ifqi09ghhssusmb0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT fk8seu7b87ifqi09ghhssusmb0x FOREIGN KEY (wallet_id) REFERENCES public.wallets(id);


--
-- Name: product_variant_images fk9jwla8t7mpnllbt5gp0le008i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variant_images
    ADD CONSTRAINT fk9jwla8t7mpnllbt5gp0le008i FOREIGN KEY (variant_id) REFERENCES public.product_variants(id);


--
-- Name: seller_stores fkbg4hkux46uggatkdxuom83w0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_stores
    ADD CONSTRAINT fkbg4hkux46uggatkdxuom83w0 FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: products fkbgw3lyxhsml3kfqnfr45o0vbj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkbgw3lyxhsml3kfqnfr45o0vbj FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: wallets fkc1foyisidw7wqqrkamafuwn4e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT fkc1foyisidw7wqqrkamafuwn4e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reviews fkcgy7qjc1r99dp117y9en6lxye; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: seller_staff fke29kra7j9tx1jke8bj0w0oqds; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_staff
    ADD CONSTRAINT fke29kra7j9tx1jke8bj0w0oqds FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_items fkemq71edpbn9wsxnxncfn1algp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkemq71edpbn9wsxnxncfn1algp FOREIGN KEY (variant_id) REFERENCES public.product_variants(id);


--
-- Name: seller_settlements fkfrlno6opywhuf9eigodee0oer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_settlements
    ADD CONSTRAINT fkfrlno6opywhuf9eigodee0oer FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: seller_staff fkgak1bfblw23b2a7i0jeabvpix; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_staff
    ADD CONSTRAINT fkgak1bfblw23b2a7i0jeabvpix FOREIGN KEY (store_id) REFERENCES public.seller_stores(id);


--
-- Name: orders fkhtx3insd5ge6w486omk4fnk54; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkhtx3insd5ge6w486omk4fnk54 FOREIGN KEY (buyer_id) REFERENCES public.users(id);


--
-- Name: product_variant_attributes fkjcp7i8t08la8masfe513eisnv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variant_attributes
    ADD CONSTRAINT fkjcp7i8t08la8masfe513eisnv FOREIGN KEY (variant_id) REFERENCES public.product_variants(id);


--
-- Name: favorites fkk7du8b8ewipawnnpg76d55fus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fkk7du8b8ewipawnnpg76d55fus FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_questions fkmb74hgsft9ibnqeb5kqile518; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_questions
    ADD CONSTRAINT fkmb74hgsft9ibnqeb5kqile518 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: seller_fulfillments fkmcxgj114axbswv8iyx4fmmhbr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_fulfillments
    ADD CONSTRAINT fkmcxgj114axbswv8iyx4fmmhbr FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: product_variants fkosqitn4s405cynmhb87lkvuau; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT fkosqitn4s405cynmhb87lkvuau FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: audit_log fkp0xyrkkoeraheio5qt1iihlo1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fkp0xyrkkoeraheio5qt1iihlo1 FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: return_evidence fkpd3f82h34prn9jetnrt1q8il8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_evidence
    ADD CONSTRAINT fkpd3f82h34prn9jetnrt1q8il8 FOREIGN KEY (return_id) REFERENCES public.return_requests(id);


--
-- Name: category_attribute_values fkpkb0sr0g1jf8qn3n1lpv0qppl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_attribute_values
    ADD CONSTRAINT fkpkb0sr0g1jf8qn3n1lpv0qppl FOREIGN KEY (attribute_id) REFERENCES public.category_attributes(id);


--
-- Name: reviews fkpl51cejpw4gy5swfar8br9ngi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkpl51cejpw4gy5swfar8br9ngi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: return_requests fkqmtolfa50ie1jxfsak1e8jnkb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkqmtolfa50ie1jxfsak1e8jnkb FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: product_images fkqnq71xsohugpqwf3c9gxmsuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: category_attributes fks8x8saggy3b3wx581pn813por; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_attributes
    ADD CONSTRAINT fks8x8saggy3b3wx581pn813por FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: categories fksaok720gsu4u2wrgbk10b5n8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES public.categories(id);


--
-- Name: refresh_tokens refresh_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


