ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(5) DEFAULT 'fr';
ALTER TABLE users ADD COLUMN IF NOT EXISTS delivery_instructions VARCHAR(500);
