CREATE TABLE IF NOT EXISTS saved_lists(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(80) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS saved_list_products(list_id BIGINT NOT NULL REFERENCES saved_lists(id) ON DELETE CASCADE,product_id BIGINT NOT NULL,PRIMARY KEY(list_id,product_id));
