import React from 'react'
import {ChevronDown,ClipboardList,PackageCheck,RefreshCw,Search,Truck,X} from 'lucide-react'
import {api} from './lib/api'
import './seller-orders.css'

// Les statuts viennent de OrderStatus cote serveur : PENDING, PROCESSING,
// SHIPPED, DELIVERED, CANCELLED. Un ancien 'PAID' figurait ici et alimentait
// une option de filtre qui ne pouvait jamais rien renvoyer.
const labels={PENDING:'En attente de paiement',PROCESSING:'En préparation',SHIPPED:'Expédiée',DELIVERED:'Livrée',CANCELLED:'Annulée'}
const money=n=>new Intl.NumberFormat('fr-FR').format(Number(n||0))+' FDJ'
export default function SellerOrdersPage(){const [orders,setOrders]=React.useState([]),[filter,setFilter]=React.useState('ALL'),[query,setQuery]=React.useState(''),[selected,setSelected]=React.useState(null),[tracking,setTracking]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('')
 const load=()=>api('/seller/orders').then(setOrders).catch(e=>setError(e.message));React.useEffect(()=>{load()},[])
 const shown=orders.filter(o=>(filter==='ALL'||o.status===filter)&&('#DT-'+o.orderId).toLowerCase().includes(query.toLowerCase()))
 async function update(status){setBusy(true);setError('');try{const updated=await api(`/seller/orders/${selected.fulfillmentId}`,{method:'PATCH',body:JSON.stringify({status,trackingNumber:status==='SHIPPED'?tracking:selected.trackingNumber})});setOrders(list=>list.map(x=>x.fulfillmentId===selected.fulfillmentId?{...x,...updated}:x));setSelected(x=>({...x,...updated}));if(status==='DELIVERED')setSelected(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="portal-content seller-orders"><header><div><small>VENTES</small><h1>Commandes</h1><p>Préparez et suivez les commandes contenant vos produits.</p></div><button onClick={load}><RefreshCw/> Actualiser</button></header><div className="seller-order-filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une commande…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Tous les statuts</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>{error&&<div className="api-error">{error}</div>}<div className="seller-orders-list"><div className="head"><span>Commande</span><span>Date</span><span>Articles</span><span>Montant</span><span>Statut</span><span/></div>{shown.map(order=><article key={order.fulfillmentId}><b>#DT-{order.orderId}</b><span>{new Date(order.createdAt).toLocaleDateString('fr-FR')}</span><span>{order.items?.reduce((n,x)=>n+x.quantity,0)||0} article(s)</span><strong>{money(order.subtotal)}</strong><em className={String(order.status).toLowerCase()}>{labels[order.status]||order.status}</em><button onClick={()=>{setSelected(order);setTracking(order.trackingNumber||'')}}>Gérer <ChevronDown/></button></article>)}</div>{!shown.length&&<div className="seller-orders-empty"><ClipboardList/><h2>Aucune commande</h2><p>Aucune commande ne correspond à ce filtre.</p></div>}
 {selected&&<div className="modal-backdrop"><section className="seller-order-drawer" role="dialog" aria-modal="true"><header><div><small>COMMANDE</small><h2>#DT-{selected.orderId}</h2><em className={String(selected.status).toLowerCase()}>{labels[selected.status]}</em></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="seller-order-date">Reçue le {new Date(selected.createdAt).toLocaleString('fr-FR')}</div><div className="seller-order-items">{selected.items?.map(item=><article key={item.id}><i>{item.product?.images?.[0]?<img src={item.product.images[0]} alt=""/>:<PackageCheck/>}</i><span><b>{item.product?.name}</b><small>Quantité : {item.quantity}</small></span><strong>{money(Number(item.price)*item.quantity)}</strong></article>)}</div><div className="seller-order-total"><span>Sous-total vendeur</span><b>{money(selected.subtotal)}</b></div>{selected.trackingNumber&&<div className="seller-tracking"><Truck/><span><small>NUMÉRO DE SUIVI</small><b>{selected.trackingNumber}</b></span></div>}{error&&<div className="api-error">{error}</div>}<footer>{selected.status==='PENDING'&&<p>Cette commande attend encore la confirmation du paiement.</p>}{selected.status==='PROCESSING'&&<><label>Numéro de suivi<input value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="Ex. DT-EXP-2026-001"/></label><button disabled={busy||!tracking.trim()} onClick={()=>update('SHIPPED')}><Truck/> Confirmer l’expédition</button></>}{selected.status==='SHIPPED'&&<button disabled={busy} onClick={()=>update('DELIVERED')}><PackageCheck/> Confirmer la livraison</button>}{['DELIVERED','CANCELLED'].includes(selected.status)&&<p>Cette commande est clôturée.</p>}</footer></section></div>}</div>}
