package com.djibtout.backend;
import com.djibtout.backend.controller.AdminController;import com.djibtout.backend.entity.*;import com.djibtout.backend.repository.*;import com.djibtout.backend.service.SellerEventService;import org.junit.jupiter.api.*;import org.mockito.*;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class AdminControllerTests{
 UserRepository users=mock(UserRepository.class);OrderRepository orders=mock(OrderRepository.class);ProductRepository products=mock(ProductRepository.class);SellerStoreRepository stores=mock(SellerStoreRepository.class);ReturnRequestRepository returns=mock(ReturnRequestRepository.class);ReviewRepository reviews=mock(ReviewRepository.class);ProductQuestionRepository questions=mock(ProductQuestionRepository.class);CouponRepository coupons=mock(CouponRepository.class);AuditLogRepository audits=mock(AuditLogRepository.class);SellerEventService events=mock(SellerEventService.class);AdminController controller=new AdminController(users,orders,products,stores,returns,reviews,questions,coupons,audits,events);
 UsernamePasswordAuthenticationToken auth(String email){return new UsernamePasswordAuthenticationToken(email,"x");}
 @Test void buyerCannotReadUsers(){User buyer=new User();buyer.setEmail("buyer@test.local");buyer.setRole(Role.BUYER);when(users.findByEmail(buyer.getEmail())).thenReturn(Optional.of(buyer));assertEquals(403,controller.users(auth(buyer.getEmail())).getStatusCode().value());}
 @Test void adminCanReadUsers(){User admin=new User();admin.setEmail("admin@test.local");admin.setRole(Role.ADMIN);when(users.findByEmail(admin.getEmail())).thenReturn(Optional.of(admin));when(users.findAll()).thenReturn(List.of(admin));assertEquals(200,controller.users(auth(admin.getEmail())).getStatusCode().value());}
 @Test void adminAccountCannotBeSuspended(){User admin=new User();admin.setEmail("admin@test.local");admin.setRole(Role.ADMIN);when(users.findByEmail(admin.getEmail())).thenReturn(Optional.of(admin));when(users.findById(1L)).thenReturn(Optional.of(admin));assertEquals(409,controller.suspend(auth(admin.getEmail()),1L,Map.of("suspended",true)).getStatusCode().value());}
}
