spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
server.error.include-message=never
server.error.include-stacktrace=never
server.forward-headers-strategy=framework
app.admin-bootstrap.enabled=false
app.media.storage=${MEDIA_STORAGE:s3}
