package com.djibtout.backend.controller;
import com.djibtout.backend.entity.*;import com.djibtout.backend.repository.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/account") public class AccountController{
 private final UserRepository users;private final OrderRepository orders;private final AddressRepository addresses;private final PasswordEncoder encoder;
 public AccountController(UserRepository u,OrderRepository o,AddressRepository a,PasswordEncoder e){users=u;orders=o;addresses=a;encoder=e;}
 private User user(Authentication auth){return auth==null?null:users.findByEmail(auth.getName()).orElse(null);}
 @GetMapping("/profile") public ResponseEntity<?> profile(Authentication auth){User u=user(auth);return u==null?ResponseEntity.status(401).build():ResponseEntity.ok(view(u));}
 @PutMapping("/profile") public ResponseEntity<?> update(Authentication auth,@Valid @RequestBody ProfileInput input){User u=user(auth);if(u==null)return ResponseEntity.status(401).build();u.setName(input.name().trim());u.setPhone(input.phone());users.save(u);return ResponseEntity.ok(view(u));}
 @PutMapping("/preferences") public ResponseEntity<?> preferences(Authentication auth,@RequestBody PreferencesInput input){User u=user(auth);if(u==null)return ResponseEntity.status(401).build();u.setOrderNotifications(input.orderNotifications());u.setPromotionNotifications(input.promotionNotifications());users.save(u);return ResponseEntity.ok(view(u));}
 @GetMapping("/export") public ResponseEntity<?> export(Authentication auth){User u=user(auth);if(u==null)return ResponseEntity.status(401).build();Map<String,Object> data=new LinkedHashMap<>();data.put("exportedAt",java.time.LocalDateTime.now());data.put("profile",view(u));data.put("addresses",addresses.findByUserOrderByIsDefaultDescIdDesc(u));data.put("orders",orders.findByBuyerOrderByCreatedAtDesc(u));return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=djibtout-data.json").body(data);}
 @DeleteMapping @Transactional public ResponseEntity<?> delete(Authentication auth,@RequestBody DeleteInput input){User u=user(auth);if(u==null)return ResponseEntity.status(401).build();if(u.getProvider()==AuthProvider.LOCAL&&!encoder.matches(input.password()==null?"":input.password(),u.getPassword()))return ResponseEntity.status(403).body(Map.of("message","Mot de passe incorrect."));String marker="deleted-"+u.getId()+"-"+UUID.randomUUID()+"@deleted.djibtout";u.setName("Compte supprimé");u.setEmail(marker);u.setPhone(null);u.setPassword(encoder.encode(UUID.randomUUID().toString()));u.setOrderNotifications(false);u.setPromotionNotifications(false);u.setAccountDeleted(true);users.save(u);return ResponseEntity.noContent().build();}
 private Map<String,Object> view(User u){Map<String,Object> value=new LinkedHashMap<>();value.put("id",u.getId());value.put("name",u.getName());value.put("email",u.getEmail());value.put("phone",u.getPhone());value.put("role",u.getRole());value.put("emailVerified",u.isEmailVerified());value.put("orderNotifications",u.isOrderNotifications());value.put("promotionNotifications",u.isPromotionNotifications());return value;}
 public record ProfileInput(@NotBlank @Size(max=100) String name,@Size(max=30) String phone){} public record PreferencesInput(boolean orderNotifications,boolean promotionNotifications){} public record DeleteInput(String password){}
}
