package com.djibtout.backend.controller;
import com.djibtout.backend.entity.*;import com.djibtout.backend.repository.*;import com.djibtout.backend.service.SellerEventService;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.time.LocalDateTime;import java.util.*;
@RestController @RequestMapping("/api/admin") public class AdminController{
 private final UserRepository users;private final OrderRepository orders;private final ProductRepository products;private final SellerStoreRepository stores;private final ReturnRequestRepository returns;private final ReviewRepository reviews;private final ProductQuestionRepository questions;private final CouponRepository coupons;private final AuditLogRepository audits;private final SellerEventService events;
 public AdminController(UserRepository u,OrderRepository o,ProductRepository p,SellerStoreRepository s,ReturnRequestRepository r,ReviewRepository v,ProductQuestionRepository q,CouponRepository c,AuditLogRepository l,SellerEventService e){users=u;orders=o;products=p;stores=s;returns=r;reviews=v;questions=q;coupons=c;audits=l;events=e;}
 private User admin(Authentication a){User u=a==null?null:users.findByEmail(a.getName()).orElse(null);return u!=null&&u.getRole()==Role.ADMIN?u:null;}
 @GetMapping("/users")public ResponseEntity<?> users(Authentication a){return admin(a)!=null?ResponseEntity.ok(users.findAll()):ResponseEntity.status(403).build();}
 @PatchMapping("/users/{id}/suspension")public ResponseEntity<?> suspend(Authentication a,@PathVariable Long id,@RequestBody Map<String,Boolean>b){User actor=admin(a);if(actor==null)return ResponseEntity.status(403).build();User u=users.findById(id).orElse(null);if(u==null)return ResponseEntity.notFound().build();if(u.getRole()==Role.ADMIN)return ResponseEntity.status(409).body("Administrateur protégé.");u.setSuspended(b.getOrDefault("suspended",true));events.audit(actor,"USER_SUSPENSION","user="+id+", suspended="+u.isSuspended());return ResponseEntity.ok(users.save(u));}
 @GetMapping("/orders")@Transactional(readOnly=true) public ResponseEntity<?> orders(Authentication a){if(admin(a)==null)return ResponseEntity.status(403).build();return ResponseEntity.ok(orders.findAll().stream().map(o->new AdminOrderSummary(o.getId(),o.getStatus(),o.getTotalAmount(),o.getDeliveryAddress(),o.getPaymentMethod(),o.getCreatedAt())).toList());}
 @PatchMapping("/orders/{id}/status")public ResponseEntity<?> orderStatus(Authentication a,@PathVariable Long id,@RequestBody Map<String,String>b){User actor=admin(a);if(actor==null)return ResponseEntity.status(403).build();Order o=orders.findById(id).orElse(null);if(o==null)return ResponseEntity.notFound().build();
  // Seule la conversion du libelle peut etre invalide. Elle est isolee : le
  // catch(Exception) englobait aussi l'enregistrement, si bien qu'une panne de
  // base ou un echec de serialisation repondait « Statut invalide. » en 400 —
  // l'administrateur corrigeait un statut qui etait deja correct.
  OrderStatus statut;
  try{statut=OrderStatus.valueOf(b.getOrDefault("status","").toUpperCase());}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body("Statut invalide.");}
  o.setStatus(statut);events.audit(actor,"ORDER_STATUS","order="+id+", status="+o.getStatus());Order saved=orders.save(o);
  // Renvoyer l'entite Order faisait echouer la serialisation sur ses proxys
  // LAZY (open-in-view=false) : le statut etait bien change, mais l'appelant
  // recevait un 500 et croyait l'operation perdue. On renvoie le meme resume
  // que GET /admin/orders.
  return ResponseEntity.ok(new AdminOrderSummary(saved.getId(),saved.getStatus(),saved.getTotalAmount(),saved.getDeliveryAddress(),saved.getPaymentMethod(),saved.getCreatedAt()));}
 // `open-in-view=false` ferme la session des la sortie du depot : lire une
 // association paresseuse apres coup levait une LazyInitializationException,
 // convertie en 500 pour l'appelant.
 @GetMapping("/returns") @Transactional(readOnly=true) public ResponseEntity<?> returns(Authentication a){return admin(a)!=null?ResponseEntity.ok(returns.findAll()):ResponseEntity.status(403).build();}
 @PatchMapping("/returns/{id}")public ResponseEntity<?> returnStatus(Authentication a,@PathVariable Long id,@RequestBody Map<String,String>b){User actor=admin(a);if(actor==null)return ResponseEntity.status(403).build();ReturnRequest r=returns.findById(id).orElse(null);if(r==null)return ResponseEntity.notFound().build();
  ReturnStatus statut;
  try{statut=ReturnStatus.valueOf(b.getOrDefault("status","").toUpperCase());}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body("Statut invalide.");}
  r.setStatus(statut);events.audit(actor,"ADMIN_RETURN_STATUS","return="+id+", status="+r.getStatus());return ResponseEntity.ok(returns.save(r));}
 @GetMapping("/reviews")public ResponseEntity<?> reviews(Authentication a){if(admin(a)==null)return ResponseEntity.status(403).build();return ResponseEntity.ok(reviews.findAll().stream().map(r->new ReviewModeration(r.getId(),r.getComment(),r.isHidden())).toList());}@PatchMapping("/reviews/{id}/moderate")public ResponseEntity<?> review(Authentication a,@PathVariable Long id,@RequestBody Map<String,Boolean>b){User actor=admin(a);Review r=reviews.findById(id).orElse(null);if(actor==null)return ResponseEntity.status(403).build();if(r==null)return ResponseEntity.notFound().build();r.setHidden(b.getOrDefault("hidden",true));events.audit(actor,"REVIEW_MODERATION","review="+id+", hidden="+r.isHidden());reviews.save(r);return ResponseEntity.ok(new ReviewModeration(r.getId(),r.getComment(),r.isHidden()));}
 @GetMapping("/questions")public ResponseEntity<?> questions(Authentication a){if(admin(a)==null)return ResponseEntity.status(403).build();return ResponseEntity.ok(questions.findAll().stream().map(q->new QuestionModeration(q.getId(),q.getQuestion(),q.isHidden())).toList());}@PatchMapping("/questions/{id}/moderate")public ResponseEntity<?> question(Authentication a,@PathVariable Long id,@RequestBody Map<String,Boolean>b){User actor=admin(a);ProductQuestion q=questions.findById(id).orElse(null);if(actor==null)return ResponseEntity.status(403).build();if(q==null)return ResponseEntity.notFound().build();q.setHidden(b.getOrDefault("hidden",true));events.audit(actor,"QUESTION_MODERATION","question="+id+", hidden="+q.isHidden());questions.save(q);return ResponseEntity.ok(new QuestionModeration(q.getId(),q.getQuestion(),q.isHidden()));}
 // Sans cette liste, masquer un produit etait irreversible : les requetes publiques filtrent
 // sur p.visible, donc un produit masque disparaissait de toute liste accessible au frontend.
 @GetMapping("/products") public ResponseEntity<?> products(Authentication a){return admin(a)!=null?ResponseEntity.ok(products.findAll()):ResponseEntity.status(403).build();}
 @PatchMapping("/products/{id}/moderate")public ResponseEntity<?> product(Authentication a,@PathVariable Long id,@RequestBody Map<String,Boolean>b){if(admin(a)==null)return ResponseEntity.status(403).build();Product p=products.findById(id).orElse(null);if(p==null)return ResponseEntity.notFound().build();p.setVisible(b.getOrDefault("visible",true));return ResponseEntity.ok(products.save(p));}
 @GetMapping("/seller-stores")public ResponseEntity<?> stores(Authentication a){return admin(a)!=null?ResponseEntity.ok(stores.findAll()):ResponseEntity.status(403).build();}@PatchMapping("/seller-stores/{id}/validation")public ResponseEntity<?> store(Authentication a,@PathVariable Long id,@RequestBody Map<String,Boolean>b){User actor=admin(a);SellerStore s=stores.findById(id).orElse(null);if(actor==null)return ResponseEntity.status(403).build();if(s==null)return ResponseEntity.notFound().build();s.setValidated(b.getOrDefault("validated",false));s.getSeller().setSuspended(b.getOrDefault("suspended",s.getSeller().isSuspended()));users.save(s.getSeller());events.audit(actor,"SELLER_STORE_CONTROL","store="+id+", validated="+s.isValidated()+", suspended="+s.getSeller().isSuspended());return ResponseEntity.ok(stores.save(s));}
 @GetMapping("/coupons")public ResponseEntity<?> coupons(Authentication a){return admin(a)!=null?ResponseEntity.ok(coupons.findAll()):ResponseEntity.status(403).build();}@PostMapping("/coupons")public ResponseEntity<?> saveCoupon(Authentication a,@RequestBody CouponInput i){if(admin(a)==null)return ResponseEntity.status(403).build();Coupon c=i.id()==null?new Coupon():coupons.findById(i.id()).orElse(new Coupon());c.setCode(i.code().trim().toUpperCase());c.setDiscountType(i.discountType());c.setDiscountValue(i.discountValue());c.setExpiresAt(i.expiresAt());c.setUsageLimit(i.usageLimit());c.setActive(i.active());return ResponseEntity.ok(coupons.save(c));}@DeleteMapping("/coupons/{id}")public ResponseEntity<?> deleteCoupon(Authentication a,@PathVariable Long id){if(admin(a)==null)return ResponseEntity.status(403).build();coupons.deleteById(id);return ResponseEntity.noContent().build();}
 @GetMapping("/audit-logs")public ResponseEntity<?> audit(Authentication a){return admin(a)!=null?ResponseEntity.ok(audits.findAll()):ResponseEntity.status(403).build();}
 public record AdminOrderSummary(Long id,OrderStatus status,BigDecimal totalAmount,String deliveryAddress,String paymentMethod,LocalDateTime createdAt){}
 public record ReviewModeration(Long id,String comment,boolean hidden){} public record QuestionModeration(Long id,String question,boolean hidden){}
 public record CouponInput(Long id,String code,DiscountType discountType,BigDecimal discountValue,LocalDateTime expiresAt,Integer usageLimit,boolean active){}
}
