package com.djibtout.backend.controller;
import com.djibtout.backend.entity.*;import com.djibtout.backend.repository.*;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/lists") public class SavedListController{
 private final SavedListRepository lists;private final UserRepository users;private final ProductRepository products;public SavedListController(SavedListRepository l,UserRepository u,ProductRepository p){lists=l;users=u;products=p;}
 private User user(Authentication a){return a==null?null:users.findByEmail(a.getName()).orElse(null);} private SavedList owned(Authentication a,Long id){User u=user(a);SavedList x=lists.findById(id).orElse(null);return u!=null&&x!=null&&x.getUser().getId().equals(u.getId())?x:null;}
 @GetMapping public ResponseEntity<?> all(Authentication a){User u=user(a);return u==null?ResponseEntity.status(401).build():ResponseEntity.ok(lists.findByUserOrderByCreatedAtDesc(u));}
 @PostMapping public ResponseEntity<?> create(Authentication a,@RequestBody Map<String,String>b){User u=user(a);String n=b.getOrDefault("name","").trim();if(u==null)return ResponseEntity.status(401).build();if(n.isBlank()||n.length()>80)return ResponseEntity.badRequest().body("Nom de liste invalide.");SavedList x=new SavedList();x.setUser(u);x.setName(n);return ResponseEntity.status(201).body(lists.save(x));}
 @PutMapping("/{id}") public ResponseEntity<?> rename(Authentication a,@PathVariable Long id,@RequestBody Map<String,String>b){SavedList x=owned(a,id);String n=b.getOrDefault("name","").trim();if(x==null)return ResponseEntity.status(403).build();if(n.isBlank()||n.length()>80)return ResponseEntity.badRequest().body("Nom de liste invalide.");x.setName(n);return ResponseEntity.ok(lists.save(x));}
 @PostMapping("/{id}/products/{productId}") public ResponseEntity<?> add(Authentication a,@PathVariable Long id,@PathVariable Long productId){SavedList x=owned(a,id);if(x==null)return ResponseEntity.status(403).build();if(!products.existsById(productId))return ResponseEntity.notFound().build();x.getProductIds().add(productId);return ResponseEntity.ok(lists.save(x));}
 @DeleteMapping("/{id}/products/{productId}") public ResponseEntity<?> remove(Authentication a,@PathVariable Long id,@PathVariable Long productId){SavedList x=owned(a,id);if(x==null)return ResponseEntity.status(403).build();x.getProductIds().remove(productId);return ResponseEntity.ok(lists.save(x));}
 @DeleteMapping("/{id}") public ResponseEntity<?> delete(Authentication a,@PathVariable Long id){SavedList x=owned(a,id);if(x==null)return ResponseEntity.status(403).build();lists.delete(x);return ResponseEntity.noContent().build();}
}
