package com.djibtout.backend.controller;
import com.djibtout.backend.entity.*;import com.djibtout.backend.repository.*;import org.springframework.http.ResponseEntity;import org.springframework.security.core.Authentication;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.LocalDateTime;import java.util.*;
@RestController @RequestMapping("/api/seller/settlements") public class SellerSettlementController{
 private final UserRepository users;private final SellerFulfillmentRepository fulfillments;private final SellerSettlementRepository settlements;
 public SellerSettlementController(UserRepository u,SellerFulfillmentRepository f,SellerSettlementRepository s){users=u;fulfillments=f;settlements=s;}
 private User seller(Authentication a){User u=a==null?null:users.findByEmail(a.getName()).orElse(null);return u!=null&&(u.getRole()==Role.SELLER||u.getRole()==Role.ADMIN)?u:null;}
 @GetMapping @Transactional public ResponseEntity<?> list(Authentication a){User seller=seller(a);if(seller==null)return ResponseEntity.status(403).build();for(SellerFulfillment f:fulfillments.findBySellerOrderByCreatedAtDesc(seller))if(f.getStatus()==OrderStatus.DELIVERED&&settlements.findByFulfillment(f).isEmpty()){BigDecimal gross=f.getOrder().getItems().stream().filter(i->i.getProduct().getSeller()!=null&&i.getProduct().getSeller().getId().equals(seller.getId())).map(i->i.getPrice().multiply(BigDecimal.valueOf(i.getQuantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);SellerSettlement x=new SellerSettlement();x.setFulfillment(f);x.setSeller(seller);x.setGrossAmount(gross);x.setCommissionAmount(gross.multiply(new BigDecimal("0.10")).setScale(2,RoundingMode.HALF_UP));x.setNetAmount(gross.subtract(x.getCommissionAmount()));settlements.save(x);}List<SellerSettlement> values=settlements.findBySellerOrderByCreatedAtDesc(seller);BigDecimal available=values.stream().filter(x->x.getStatus()==SellerSettlementStatus.AVAILABLE).map(SellerSettlement::getNetAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal paid=values.stream().filter(x->x.getStatus()==SellerSettlementStatus.PAID).map(SellerSettlement::getNetAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return ResponseEntity.ok(Map.of("commissionRate",10,"available",available,"paid",paid,"settlements",values));}
 @PatchMapping("/admin/{id}/paid") public ResponseEntity<?> paid(Authentication a,@PathVariable Long id){User admin=seller(a);SellerSettlement x=settlements.findById(id).orElse(null);if(admin==null||admin.getRole()!=Role.ADMIN||x==null)return ResponseEntity.status(403).build();x.setStatus(SellerSettlementStatus.PAID);x.setPaidAt(LocalDateTime.now());return ResponseEntity.ok(settlements.save(x));}
}
